function ModalInfo(props) {

    return (
      <div>
        <div class="modal fade" id="modalInfo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">What is Hangman &amp; how to play</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <h4>Objective</h4>
                <p>Guess the word before your man gets hung!</p>

                <h4>Game Play</h4>
                <p>
                    A random word is generated by the game and you'll try to guess what it is one letter at a time.
                    Below the drawing there will be number of dashes equivalent to the number of letters in the word.
                    Click on any letter below that you think occurs in the mystery word. If you guessed right it will 
                    be filled in the blanks with that letter in the right places. If the word does not contain your 
                    suggested letter, the game draws one element of a hangman’s gallows.  As the game progresses, a 
                    segment of the gallows and of a victim is added for every suggested letter not in the word.
                    Completing a character in a noose provides a maximum of 11 wrong answers before you lose the game.
                </p>

                <span className="lead">Hint!</span>
                <p>
                    Try starting with letters that are most common in the English language.
                </p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-success mx-auto" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>    
      </div>
    )
  }
  
  export default ModalInfo